@startuml
skin rose

header Mastermind context
title Match
right footer (CC-BY-SA) 2022, RGV

start
:Decide each player roles;
repeat
    :Prepare board;
    :Codemaker places secret code;
    while (completed round?)
        -> no;
        :Play round;
    endwhile
    -> [feedback == 4 black pegs];
    :Add round points;
    backward:Switch roles;
repeat while (there is a match winner?)
-> [any player points >= \npoints to win match];
stop

@enduml
